name = input("Enter your name: ")
print(name)
middle_name = input("Enter your middle name: ")
print(middle_name)
surname = input("Enter your surname: ")
print(surname)
dob = input("Enter your date of birth (mm/dd/yy): ")
print(dob)
postal_code = input("Enter your postal code: ")
print(postal_code)
age = int(input("enter your age: "))
print(age)
print(f"You are: {name} {middle_name} {surname}, your age is:{age}, your postal code is: {postal_code}")

